title: Grigory's Typed Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
site-twitter: #if your site has a twitter account, enter it here
about-links: > 
  <ul class="extra-links">
    <li><a href="https://path-to-recschemes.pomadchin.com/" target="_blank">Path to Rec. Schemes slides</a></li>
    <li><a href="https://www.slideshare.net/GrigoryPomadchin/" target="_blank">SlideShare</a>
    <li><a href="https://pomadchin.com/presentations/" target="_blank">Presentations / slides / articles</a>
    <li><a href="https://www.semanticscholar.org/paper/A-Type-theoretic-Approach-to-Cloud-Data-Integration-Shapkin-Pomadchin/9d5dbfe5372e1303f4c83afd6fb44a868db3171c" target="_blank">A Type-theoretic Approach to Cloud Data Integration</a></li>
  </ul>

# Author Settings
author: Grigory Pomadchin # add your name
author-img: grigory.png # add your photo
about-author: lambda style open source software engineer on the @geotrellis team <hr /> @ScalalazPodcast host since the end of 2016
social-twitter: daunnc
social-facebook: gr.pomadchin
social-github: pomadchin
social-linkedin: grpomadchin
social-email: gr.pomadchin@gmail.com

# Disqus
discus-identifier: typedblog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
